config/urls.py
from django.contrib import admin
from django.urls import path, include
from groups.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('group/', include('groups.urls')),
    path('student/', include('students.urls')),
    path('teacher/', include('teachers.urls')),
]

groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('list/', views.gorups_list, name='list'),
    path('create/', views.groups_create, name='create'),
    path('detail/<int:pk>/', views.groups_detail, name='detail'),
    path('delete/<int:pk>/', views.groups_del, name='delete'),
]

students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('list/', views.students_list, name='list'),
    path('create/', views.students_create, name='create'),
    path('detail/<int:pk>/', views.students_detail, name='detail'),
    path('delete/<int:pk>/', views.students_del, name='delete'),
]

teachers/urls.py
from django.urls import path
from . import views

app_name = 'teachers'

urlpatterns = [
    path('list/', views.teachers_list, name='list'),
    path('create/', views.teachers_create, name='create'),
    path('detail/<int:pk>/', views.teachers_detail, name='detail'),
    path('delete/<int:pk>/', views.teachers_del, name='delete'),
]

groups/models.py
from django.db import models


class Group(models.Model):
    g_name = models.CharField(max_length=100)
    g_type = models.CharField(max_length=100)

students/models.py
from django.db import models


class Student(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    age = models.IntegerField()
    email = models.TextField()

teachers/models.py
from django.db import models


class Teacher(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    subjects = models.CharField(max_length=100)

groups/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Group


def home(request):
    return render(request, 'index.html')


def gorups_list(request):
    g_list = Group.objects.all
    ctx = {'g_list': g_list}
    return render(request, 'group/group_list.html', ctx)


def groups_create(request):
    if request.method == 'POST':
        g_name = request.POST.get('g_name')
        g_type = request.POST.get('g_type')
        if g_name and g_type:
            Group.objects.create(
                g_name = g_name,
                g_type = g_type,
            )
            return redirect('groups:list')
    return render(request, 'group/group_create.html')


def groups_detail(request, pk):
    group = get_object_or_404(Group, pk=pk)
    ctx = {'group': group}
    return render(request, 'group/group_detail.html', ctx)


def groups_del(request, pk):
    group = get_object_or_404(Group, pk=pk)
    group.delete()
    return redirect('groups:list')

students/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Student


def students_list(request):
    s_list = Student.objects.all
    ctx = {'s_list': s_list}
    return render(request, 'student/student_list.html', ctx)


def students_create(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        age = request.POST.get('age')
        email = request.POST.get('email')
        if first_name and last_name and age and email:
            Student.objects.create(
                first_name=first_name,
                last_name=last_name,
                age=age,
                email=email,
            )
            return redirect('students:list')
    return render(request, 'student/student_create.html')


def students_detail(request, pk):
    student = get_object_or_404(Student, pk=pk)
    ctx = {'student': student}
    return render(request, 'student/student_detail.html', ctx)


def students_del(request, pk):
    student = get_object_or_404(Student, pk=pk)
    student.delete()
    return redirect('students:list')

teachers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Teacher


def teachers_list(request):
    t_list = Teacher.objects.all
    ctx = {'t_list': t_list}
    return render(request, 'teacher/teacher_list.html', ctx)


def teachers_create(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        subjects = request.POST.get('subjects')
        if first_name and last_name and subjects:
            Teacher.objects.create(
                first_name=first_name,
                last_name=last_name,
                subjects=subjects,
            )
            return redirect('teachers:list')
    return render(request, 'teacher/teacher_create.html')


def teachers_detail(request, pk):
    teacher = get_object_or_404(Teacher, pk=pk)
    ctx = {'teacher': teacher}
    return render(request, 'teacher/teacher_detail.html', ctx)


def teachers_del(request, pk):
    teacher = get_object_or_404(Teacher, pk=pk)
    teacher.delete()
    return redirect('teachers:list')

templates/group/group_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Group Create</title>
</head>
<body>
    <h1>Group Create</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="g_name">Group Name</label><br>
        <input type="text" name="g_name" id="g_name"><br>
        <label for="g_type">Group Type</label><br>
        <input type="text" name="g_type" id="g_type"><br><br>
        <button type="submit">Create Group</button>
    </form>
    <br>
    <button><a href="{% url 'groups:list' %}">Back to group list</a></button>
    <br>
    <br>
    <button><a href="{% url 'home' %}">Back to home</a></button>
</body>
</html>

templates/group/group_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ group.g_name }}</title>
</head>
<body>
    <h1>{{ group.g_name }}</h1>
    <h3>Group Name: {{group.g_name}}</h3>
    <h3>Group Type: {{group.g_type}}</h3>
    <button><a href="{% url 'groups:delete' pk=group.pk %}">Delete</a></button>
    <br>
    <br>
    <button><a href="{% url 'groups:list' %}">Back to group list</a></button>
</body>
</html>

templates/group/group_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Group List</title>
</head>
<body>
    <h1>Group List</h1>
    <button><a href="{% url 'groups:create' %}">Create Group</a></button>
    <br>
    <br>
    <button><a href="{% url 'home' %}">Back to home</a></button>
    {% for group in g_list %}
        <a href="{% url 'groups:detail' pk=group.pk %}"><h3>{{ group.g_name }}</h3></a>
    {% empty %}
        <h3>No group</h3>
    {% endfor %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
</head>
<body>
    <h1>Home Page</h1>
    <a href="{% url 'groups:list' %}">Groups</a><br>
    <a href="{% url 'students:list' %}">Students</a><br>
    <a href="{% url 'teachers:list' %}">Teachers</a><br>
</body>
</html>

templates/student/student_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Create</title>
</head>
<body>
    <h1>Student Create</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="first_name">First Name</label><br>
        <input type="text" name="first_name" id="first_name"><br>
        <label for="last_name">Last Name</label><br>
        <input type="text" name="last_name" id="last_name"><br>
        <label for="age">Age</label><br>
        <input type="number" name="age" id="age"><br>
         <label for="email">Email</label><br>
        <input type="email" name="email" id="email"><br><br>
        <button type="submit">Create Student</button>
    </form>
    <br>
    <button><a href="{% url 'students:list' %}">Back to student list</a></button>
    <br>
    <br>
    <button><a href="{% url 'home' %}">Back to home</a></button>
</body>
</html>

templates/student/student_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ student.first_name }} {{ student.last_name }}</title>
</head>
<body>
    <h1>{{ student.first_name }} {{ student.last_name }}</h1>
    <h3>First Name: {{student.first_name}}</h3>
    <h3>Last Name: {{student.last_name}}</h3>
    <h3>Age: {{student.age}}</h3>
    <h3>Email: {{student.email}}</h3>
    <button><a href="{% url 'students:delete' pk=student.pk %}">Delete</a></button>
    <br>
    <br>
    <button><a href="{% url 'students:list' %}">Back to student list</a></button>
</body>
</html>

templates/student/student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student List</title>
</head>
<body>
    <h1>Student List</h1>
    <button><a href="{% url 'students:create' %}">Create Student</a></button>
    <br>
    <br>
    <button><a href="{% url 'home' %}">Back to home</a></button>
    {% for student in s_list %}
        <a href="{% url 'students:detail' pk=student.pk %}"><h3>{{ student.first_name }} {{ student.last_name }}</h3></a>
    {% empty %}
        <h3>No student</h3>
    {% endfor %}
</body>
</html>

templates/teacher/teacher_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher Create</title>
</head>
<body>
    <h1>Teacher Create</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="first_name">First Name</label><br>
        <input type="text" name="first_name" id="first_name"><br>
        <label for="last_name">Last Name</label><br>
        <input type="text" name="last_name" id="last_name"><br>
        <label for="subjects">Subject</label><br>
        <input type="text" name="subjects" id="subjects"><br>
        <button type="submit">Create Teacher</button>
    </form>
    <br>
    <button><a href="{% url 'teachers:list' %}">Back to teacher list</a></button>
    <br>
    <br>
    <button><a href="{% url 'home' %}">Back to home</a></button>
</body>
</html>

templates/teacher/teacher_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ teacher.first_name }} {{ teacher.last_name }}</title>
</head>
<body>
    <h1>{{ teacher.first_name }} {{ teacher.last_name }}</h1>
    <h3>First Name: {{teacher.first_name}}</h3>
    <h3>Last Name: {{teacher.last_name}}</h3>
    <h3>Subject: {{student.subjects}}</h3>
    <button><a href="{% url 'teachers:delete' pk=teacher.pk %}">Delete</a></button>
    <br>
    <button><a href="{% url 'teachers:list' %}">Back to teacher list</a></button>
</body>
</html>

templates/teacher/teacher_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher List</title>
</head>
<body>
    <h1>Teacher List</h1>
    <button><a href="{% url 'teachers:create' %}">Create Teacher</a></button>
    <br>
    <br>
    <button><a href="{% url 'home' %}">Back to home</a></button>
    {% for teacher in t_list %}
        <a href="{% url 'teachers:detail' pk=teacher.pk %}"><h3>{{ teacher.first_name }} {{ teacher.last_name }}</h3></a>
    {% empty %}
        <h3>No teacher</h3>
    {% endfor %}
</body>
</html>